const { env: {
  PORT,
  POSTGRES_USER,
  POSTGRES_PASSWORD,
  POSTGRES_DB,
  POSTGRES_HOST,
  POSTGRES_PORT,
  ENABLE_SWAGGER,
  SWAGGER_SECRET_KEY,
  ENABLE_LOG_DEBUG,
} } = process;

export default {
  PORT: PORT || 8080,
  DB_USER: POSTGRES_USER || 'api',
  DB_PASSWORD: POSTGRES_PASSWORD || 'api',
  DB_SCHEMA: POSTGRES_DB || 'shipjs',
  DB_PORT: POSTGRES_PORT || 5004,
  DB_HOST: POSTGRES_HOST || '127.0.0.1',
  ENABLE_SWAGGER,
  SWAGGER_SECRET_KEY,
  ENABLE_LOG_DEBUG,
};
